In [1]:
import numpy as np

In [2]:
air_threshold = 5

In [3]:
app_no = 5

In [4]:
fridge_data = np.load('UKData/Fridge freezer0.npy')
print(fridge_data.shape)
fridge_data = fridge_data[:1600000]
print(fridge_data.shape)
fridge_data = np.where(fridge_data > air_threshold,fridge_data,0)

television_data = np.load('UKData/Television0.npy')
print(television_data.shape)
television_data = television_data[:1600000]
print(television_data.shape)
television_data = np.where(television_data > air_threshold, television_data,0)


microwave_data = np.load('UKData/Microwave0.npy')
print(microwave_data.shape)
microwave_data = microwave_data[:1600000]
print(microwave_data.shape)
microwave_data = np.where(microwave_data > air_threshold, microwave_data,0)

washerdryer_data = np.load('UKData/Washer dryer0.npy')
print(washerdryer_data.shape)
washerdryer_data = washerdryer_data[:1600000]
print(washerdryer_data.shape)
washerdryer_data = np.where(washerdryer_data > air_threshold, washerdryer_data,0)


boiler_data = np.load('UKData/Boiler0.npy')
print(boiler_data.shape)
boiler_data = boiler_data[:1600000]
print(boiler_data.shape)
boiler_data = np.where(boiler_data > air_threshold,boiler_data,0)

(8010973, 1)
(1600000, 1)
(8074277, 1)
(1600000, 1)
(8054586, 1)
(1600000, 1)
(7945298, 1)
(1600000, 1)
(8821597, 1)
(1600000, 1)


In [5]:
sum_data = fridge_data + television_data + microwave_data + washerdryer_data + boiler_data

app_data = [fridge_data,television_data,microwave_data,washerdryer_data,boiler_data]

In [6]:
app_data[0].shape

(1600000, 1)

In [7]:
step =400
window_size=800
total_len=1600000

In [8]:
print(sum_data[i,0])

NameError: name 'i' is not defined

In [47]:
temp_start = 0
sum_data_agg =[]
while temp_start+window_size <=total_len:
    temp_data_agg =[]
    for i in range (temp_start,temp_start+window_size):
        temp_data_agg.append(sum_data[i,0])
    sum_data_agg.append(temp_data_agg)
    temp_start += step
    print(temp_start)
sum_data_agg=np.array(sum_data_agg)

400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
9200
9600
10000
10400
10800
11200
11600
12000
12400
12800
13200
13600
14000
14400
14800
15200
15600
16000
16400
16800
17200
17600
18000
18400
18800
19200
19600
20000
20400
20800
21200
21600
22000
22400
22800
23200
23600
24000
24400
24800
25200
25600
26000
26400
26800
27200
27600
28000
28400
28800
29200
29600
30000
30400
30800
31200
31600
32000
32400
32800
33200
33600
34000
34400
34800
35200
35600
36000
36400
36800
37200
37600
38000
38400
38800
39200
39600
40000
40400
40800
41200
41600
42000
42400
42800
43200
43600
44000
44400
44800
45200
45600
46000
46400
46800
47200
47600
48000
48400
48800
49200
49600
50000
50400
50800
51200
51600
52000
52400
52800
53200
53600
54000
54400
54800
55200
55600
56000
56400
56800
57200
57600
58000
58400
58800
59200
59600
60000
60400
60800
61200
61600
62000
62400
62800
63200
63600
64000
64400
64800
65200
65600
66000
66400
66800
67200
67600
68000
68400


651200
651600
652000
652400
652800
653200
653600
654000
654400
654800
655200
655600
656000
656400
656800
657200
657600
658000
658400
658800
659200
659600
660000
660400
660800
661200
661600
662000
662400
662800
663200
663600
664000
664400
664800
665200
665600
666000
666400
666800
667200
667600
668000
668400
668800
669200
669600
670000
670400
670800
671200
671600
672000
672400
672800
673200
673600
674000
674400
674800
675200
675600
676000
676400
676800
677200
677600
678000
678400
678800
679200
679600
680000
680400
680800
681200
681600
682000
682400
682800
683200
683600
684000
684400
684800
685200
685600
686000
686400
686800
687200
687600
688000
688400
688800
689200
689600
690000
690400
690800
691200
691600
692000
692400
692800
693200
693600
694000
694400
694800
695200
695600
696000
696400
696800
697200
697600
698000
698400
698800
699200
699600
700000
700400
700800
701200
701600
702000
702400
702800
703200
703600
704000
704400
704800
705200
705600
706000
706400
706800
707200
707600
708000

1231600
1232000
1232400
1232800
1233200
1233600
1234000
1234400
1234800
1235200
1235600
1236000
1236400
1236800
1237200
1237600
1238000
1238400
1238800
1239200
1239600
1240000
1240400
1240800
1241200
1241600
1242000
1242400
1242800
1243200
1243600
1244000
1244400
1244800
1245200
1245600
1246000
1246400
1246800
1247200
1247600
1248000
1248400
1248800
1249200
1249600
1250000
1250400
1250800
1251200
1251600
1252000
1252400
1252800
1253200
1253600
1254000
1254400
1254800
1255200
1255600
1256000
1256400
1256800
1257200
1257600
1258000
1258400
1258800
1259200
1259600
1260000
1260400
1260800
1261200
1261600
1262000
1262400
1262800
1263200
1263600
1264000
1264400
1264800
1265200
1265600
1266000
1266400
1266800
1267200
1267600
1268000
1268400
1268800
1269200
1269600
1270000
1270400
1270800
1271200
1271600
1272000
1272400
1272800
1273200
1273600
1274000
1274400
1274800
1275200
1275600
1276000
1276400
1276800
1277200
1277600
1278000
1278400
1278800
1279200
1279600
1280000
1280400
1280800
1281200


In [13]:
#appliance aggregation
temp_start = 0
sum_appliance_agg =[]
while temp_start+window_size <=total_len:
    temp_appliances_agg =[]
    for i in range(app_no):
        
        
        temp_appliance_agg=[]
        for j in range (temp_start,temp_start+window_size):
            
            temp_appliance_agg.append(app_data[i][j,0])
            
        temp_appliances_agg.append(temp_appliance_agg)
        
    
    sum_appliance_agg.append(temp_appliances_agg)
    temp_start += step
    print(temp_start)

400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
9200
9600
10000
10400
10800
11200
11600
12000
12400
12800
13200
13600
14000
14400
14800
15200
15600
16000
16400
16800
17200
17600
18000
18400
18800
19200
19600
20000
20400
20800
21200
21600
22000
22400
22800
23200
23600
24000
24400
24800
25200
25600
26000
26400
26800
27200
27600
28000
28400
28800
29200
29600
30000
30400
30800
31200
31600
32000
32400
32800
33200
33600
34000
34400
34800
35200
35600
36000
36400
36800
37200
37600
38000
38400
38800
39200
39600
40000
40400
40800
41200
41600
42000
42400
42800
43200
43600
44000
44400
44800
45200
45600
46000
46400
46800
47200
47600
48000
48400
48800
49200
49600
50000
50400
50800
51200
51600
52000
52400
52800
53200
53600
54000
54400
54800
55200
55600
56000
56400
56800
57200
57600
58000
58400
58800
59200
59600
60000
60400
60800
61200
61600
62000
62400
62800
63200
63600
64000
64400
64800
65200
65600
66000
66400
66800
67200
67600
68000
68400


540000
540400
540800
541200
541600
542000
542400
542800
543200
543600
544000
544400
544800
545200
545600
546000
546400
546800
547200
547600
548000
548400
548800
549200
549600
550000
550400
550800
551200
551600
552000
552400
552800
553200
553600
554000
554400
554800
555200
555600
556000
556400
556800
557200
557600
558000
558400
558800
559200
559600
560000
560400
560800
561200
561600
562000
562400
562800
563200
563600
564000
564400
564800
565200
565600
566000
566400
566800
567200
567600
568000
568400
568800
569200
569600
570000
570400
570800
571200
571600
572000
572400
572800
573200
573600
574000
574400
574800
575200
575600
576000
576400
576800
577200
577600
578000
578400
578800
579200
579600
580000
580400
580800
581200
581600
582000
582400
582800
583200
583600
584000
584400
584800
585200
585600
586000
586400
586800
587200
587600
588000
588400
588800
589200
589600
590000
590400
590800
591200
591600
592000
592400
592800
593200
593600
594000
594400
594800
595200
595600
596000
596400
596800

1058000
1058400
1058800
1059200
1059600
1060000
1060400
1060800
1061200
1061600
1062000
1062400
1062800
1063200
1063600
1064000
1064400
1064800
1065200
1065600
1066000
1066400
1066800
1067200
1067600
1068000
1068400
1068800
1069200
1069600
1070000
1070400
1070800
1071200
1071600
1072000
1072400
1072800
1073200
1073600
1074000
1074400
1074800
1075200
1075600
1076000
1076400
1076800
1077200
1077600
1078000
1078400
1078800
1079200
1079600
1080000
1080400
1080800
1081200
1081600
1082000
1082400
1082800
1083200
1083600
1084000
1084400
1084800
1085200
1085600
1086000
1086400
1086800
1087200
1087600
1088000
1088400
1088800
1089200
1089600
1090000
1090400
1090800
1091200
1091600
1092000
1092400
1092800
1093200
1093600
1094000
1094400
1094800
1095200
1095600
1096000
1096400
1096800
1097200
1097600
1098000
1098400
1098800
1099200
1099600
1100000
1100400
1100800
1101200
1101600
1102000
1102400
1102800
1103200
1103600
1104000
1104400
1104800
1105200
1105600
1106000
1106400
1106800
1107200
1107600


1505200
1505600
1506000
1506400
1506800
1507200
1507600
1508000
1508400
1508800
1509200
1509600
1510000
1510400
1510800
1511200
1511600
1512000
1512400
1512800
1513200
1513600
1514000
1514400
1514800
1515200
1515600
1516000
1516400
1516800
1517200
1517600
1518000
1518400
1518800
1519200
1519600
1520000
1520400
1520800
1521200
1521600
1522000
1522400
1522800
1523200
1523600
1524000
1524400
1524800
1525200
1525600
1526000
1526400
1526800
1527200
1527600
1528000
1528400
1528800
1529200
1529600
1530000
1530400
1530800
1531200
1531600
1532000
1532400
1532800
1533200
1533600
1534000
1534400
1534800
1535200
1535600
1536000
1536400
1536800
1537200
1537600
1538000
1538400
1538800
1539200
1539600
1540000
1540400
1540800
1541200
1541600
1542000
1542400
1542800
1543200
1543600
1544000
1544400
1544800
1545200
1545600
1546000
1546400
1546800
1547200
1547600
1548000
1548400
1548800
1549200
1549600
1550000
1550400
1550800
1551200
1551600
1552000
1552400
1552800
1553200
1553600
1554000
1554400
1554800


In [14]:
sum_appliance_agg=np.array(sum_appliance_agg)

In [15]:
print(sum_appliance_agg.shape)

(3999, 5, 800)


In [12]:
temp_appliance_agg=np.array(temp_appliance_agg)
print(temp_appliance_agg.shape)

(800,)


In [16]:
test = sum_appliance_agg[:400,:]

In [17]:
print(test.shape)

(400, 5, 800)


In [18]:
print(test[0])

[[ 0.  0.  0. ... 89. 88. 87.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. 12. ... 12. 12. 12.]]
