In [58]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

In [2]:
air_threshold = 5

In [3]:
app_no = 5

In [4]:
fridge_data = np.load('UKData/Fridge freezer0.npy')
print(fridge_data.shape)
fridge_data = fridge_data[:1600000]
print(fridge_data.shape)
fridge_data = np.where(fridge_data > air_threshold,fridge_data,0)

television_data = np.load('UKData/Television0.npy')
print(television_data.shape)
television_data = television_data[:1600000]
print(television_data.shape)
television_data = np.where(television_data > air_threshold, television_data,0)


microwave_data = np.load('UKData/Microwave0.npy')
print(microwave_data.shape)
microwave_data = microwave_data[:1600000]
print(microwave_data.shape)
microwave_data = np.where(microwave_data > air_threshold, microwave_data,0)

washerdryer_data = np.load('UKData/Washer dryer0.npy')
print(washerdryer_data.shape)
washerdryer_data = washerdryer_data[:1600000]
print(washerdryer_data.shape)
washerdryer_data = np.where(washerdryer_data > air_threshold, washerdryer_data,0)


boiler_data = np.load('UKData/Boiler0.npy')
print(boiler_data.shape)
boiler_data = boiler_data[:1600000]
print(boiler_data.shape)
boiler_data = np.where(boiler_data > air_threshold,boiler_data,0)

(8010973, 1)
(1600000, 1)
(8074277, 1)
(1600000, 1)
(8054586, 1)
(1600000, 1)
(7945298, 1)
(1600000, 1)
(8821597, 1)
(1600000, 1)


In [ ]:
#need to do##### Batch loading

In [47]:
sum_data = fridge_data + television_data + microwave_data + washerdryer_data + boiler_data

app_data = [fridge_data,television_data,microwave_data,washerdryer_data,boiler_data]

In [48]:
#Yi qing Part   MinmaxScale/Normalization/ Standardization

In [98]:
def Data_MinMaxScale(data):
    scaler = MinMaxScaler(feature_range=(0,1))
    scaled_data = scaler.fit_transform(data)
    return scaled_data

def Data_Standardization(data):
    
    scaled_data = preprocessing.scale(data)
    return scaled_data

def Data_Normalization(data):
    
    scaled_data = preprocessing.normalize(data,norm='l2')
    return scaled_data

In [139]:
print(sum_data_agg[0:200])
scaled_sum_data = Data_Standardization(sum_data_agg)
print(scaled_sum_data.shape)
print(scaled_sum_data)

[[  0.   0.  12. ... 101. 100.  99.]
 [ 98.  98.  12. ...  12.  12.  12.]
 [ 98.  97.  97. ...  12.  12.  12.]
 ...
 [ 97.  85.  98. ...  76.  76.  76.]
 [ 12.  12.  12. ...  12.  12.  12.]
 [ 78.  79.  82. ... 321. 392.  46.]]
(3999, 800)
[[-0.8644623  -0.86932194 -0.7048366  ...  0.47407678  0.4504763
   0.4441217 ]
 [ 0.4174575   0.43086344 -0.7048366  ... -0.7065648  -0.7105509
  -0.708483  ]
 [ 0.4174575   0.41759622  0.40760082 ... -0.7065648  -0.7105509
  -0.708483  ]
 ...
 [ 0.37821504  0.40432903  0.3945133  ...  1.6547183   0.3977023
   0.39112836]
 [-0.8644623  -0.86932194 -0.86188656 ...  0.28835788  0.27896088
   0.28514174]
 [ 0.39129585  0.39106184  0.38142583 ...  0.39448297  0.37131533
   0.39112836]]


C:\Users\Raytine\anaconda3\envs\kera\lib\site-packages\scikit_learn-0.24.1-py3.7-win-amd64.egg\sklearn\preprocessing\_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
C:\Users\Raytine\anaconda3\envs\kera\lib\site-packages\scikit_learn-0.24.1-py3.7-win-amd64.egg\sklearn\preprocessing\_data.py:211: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "


In [108]:
print(sum_data_agg[0:200])
scaled_sum_data = Data_Normalization(sum_data_agg)

print(scaled_sum_data.shape)
print(scaled_sum_data[0:200])

[[   0.    0.   12. ...  101.  100.   99.]
 [  98.   98.   12. ...   12.   12.   12.]
 [  98.   97.   97. ...   12.   12.   12.]
 ...
 [  97.   85.   98. ...   76.   76.   76.]
 [  12.   12.   12. ...   12.   12.   12.]
 [  78.   79.   82. ...  421. 1592.   46.]]
(3999, 800)
[[0.         0.         0.0029279  ... 0.02464313 0.02439914 0.02415515]
 [0.02605338 0.02605338 0.00319021 ... 0.00319021 0.00319021 0.00319021]
 [0.05157537 0.05104909 0.05104909 ... 0.00631535 0.00631535 0.00631535]
 ...
 [0.05958645 0.05221493 0.06020074 ... 0.04668629 0.04668629 0.04668629]
 [0.0047225  0.0047225  0.0047225  ... 0.0047225  0.0047225  0.0047225 ]
 [0.01897275 0.01921599 0.01994571 ... 0.10240422 0.38723877 0.01118906]]


In [101]:
sum_data = fridge_data + television_data + microwave_data + washerdryer_data + boiler_data
scaled_sum_data = Data_MinMaxScale(sum_data)
print(scaled_sum_data.shape)
print(scaled_sum_data)

(1600000, 1)
[[0.        ]
 [0.        ]
 [0.00282087]
 ...
 [0.02233192]
 [0.02209685]
 [0.02233192]]


In [137]:
scaled_sum_data = Data_MinMaxScale(sum_data_agg)
print(scaled_sum_data.shape)
print(scaled_sum_data)

(3999, 800)
[[0.         0.         0.03015075 ... 0.25440806 0.25062656 0.2506329 ]
 [0.24561404 0.24623115 0.03015075 ... 0.0302267  0.03007519 0.03037975]
 [0.24561404 0.2437186  0.2437186  ... 0.0302267  0.03007519 0.03037975]
 ...
 [0.23809524 0.24120602 0.24120602 ... 0.47858942 0.24060151 0.24050634]
 [0.         0.         0.         ... 0.21914357 0.21804512 0.22025317]
 [0.24060151 0.23869346 0.23869346 ... 0.23929471 0.23558897 0.24050634]]


array([[ 0.],
       [ 0.],
       [12.],
       ...,
       [95.],
       [94.],
       [95.]], dtype=float32)

In [ ]:
#Zhen Part  data aggregation with slide window

In [6]:
app_data[0].shape

(1600000, 1)

In [7]:
step =400
window_size=800
total_len=1600000

In [132]:
temp_start = 0
sum_data_agg =[]
while temp_start+window_size <=total_len:
    temp_data_agg =[]
    for i in range (temp_start,temp_start+window_size):
        temp_data_agg.append(sum_data[i,0])
    sum_data_agg.append(temp_data_agg)
    temp_start += step
    
sum_data_agg=np.array(sum_data_agg)

In [9]:
#appliance aggregation
temp_start = 0
sum_appliance_agg =[]
while temp_start+window_size <=total_len:
    temp_appliances_agg =[]
    for i in range(app_no):
        
        
        temp_appliance_agg=[]
        for j in range (temp_start,temp_start+window_size):
            
            temp_appliance_agg.append(app_data[i][j,0])
            
        temp_appliances_agg.append(temp_appliance_agg)
        
    
    sum_appliance_agg.append(temp_appliances_agg)
    temp_start += step
    

In [131]:
sum_appliance_agg=np.array(sum_appliance_agg)

In [11]:
print(sum_appliance_agg.shape)
print(sum_data_agg.shape)

(3999, 5, 800)
(3999, 800)


In [143]:
print(sum_appliance_agg)


[[[  0.   0.   0. ...  89.  88.  87.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.  12. ...  12.  12.  12.]]

 [[ 86.  86.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [ 12.  12.  12. ...  12.  12.  12.]]

 [[ 86.  85.  85. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [ 12.  12.  12. ...  12.  12.  12.]]

 ...

 [[ 95.  96.  96. ... 190.  96.  95.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...  87.  87.  87.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[ 96.  95.  95. ...  95.  94.  9

In [142]:
print(sum_data_agg)

[[  0.   0.  12. ... 101. 100.  99.]
 [ 98.  98.  12. ...  12.  12.  12.]
 [ 98.  97.  97. ...  12.  12.  12.]
 ...
 [ 95.  96.  96. ... 190.  96.  95.]
 [  0.   0.   0. ...  87.  87.  87.]
 [ 96.  95.  95. ...  95.  94.  95.]]


In [12]:
temp_appliance_agg=np.array(temp_appliance_agg)
print(temp_appliance_agg.shape)

(800,)


In [134]:
#decrease too large value
max_threshold = 300 #manually setted according to the selected appliance
for i in range (sum_data_agg.shape[0]):
    for j in range (sum_data_agg.shape[1]):
        if sum_data_agg[i][j]>max_threshold:
            sum_data_agg[i][j] = ((sum_data_agg[i][j]%100) + max_threshold)

In [135]:
sum_data_agg[0]

array([  0.,   0.,  12.,  12.,   0.,  12.,   0.,   0.,  12.,  12.,   0.,
         0.,  12.,  12.,   0.,   0.,   0.,  12.,  12.,   0.,  12.,   0.,
         0.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,
        12.,   0.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,   0.,
       111., 104., 103., 102., 101., 101., 100., 100.,  99., 100., 100.,
        97.,  95.,  95.,  95.,  96.,  95.,  95.,  95.,  83.,  95.,  84.,
        96.,  96.,  96.,  96.,  98.,  97.,  98.,  98.,  99.,  99.,  99.,
        99.,  99.,  99., 100.,  99., 100., 100., 101., 100., 100., 101.,
       100., 101., 101., 101., 101., 101., 101., 101., 100., 101., 101.,
       101., 101., 101., 101., 101., 102., 101., 101., 100., 101., 101.,
       101., 102., 100., 100., 100.,  89., 100.,  99., 100., 100.,  99.,
        99.,  99.,  98.,  99.,  99.,  98.,  99.,  98.,  98.,  99.,  98.,
        98.,  98.,  98.,  98.,  98.,  98.,  99.,  98.,  98.,  98.,  98.,
        98.,  98.,  98.,  98.,  98.,  98.,  98.,  9

In [129]:
sum_data_agg[0][0] %100

3.0